version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: toor
    ports:
      - "3333:8080"
    command: start-dev
