version: "3.9"

services:
  min.io:
    hostname: min.io
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data/minio
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./esdata:/data/minio
volumes:
  esdata:
    driver: local
