version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - databases:/var/lib/mysql
volumes:
  databases: